@echo off
git pull
cd myfiziq-android
git pull
cd ..\myfiziq-sdk-android
git pull
cd ..\myfiziqsdk-android-cpp
git pull
cd ..\myfiziqsdk-android-cpp\src\main\cpp\myfiziq-sdk-cpp-utils
git pull
cd ..\..\..\..\..\myfiziqsdk-android-input
git pull
cd ..\myfiziqsdk-android-onboarding
git pull
cd ..\myfiziqsdk-android-profile
git pull
cd ..\myfiziqsdk-android-track
git pull
cd ..